# render.yaml
services:
  - type: web
    name: rest-api
    runtime: docker
    repo: https://github.com/Msaadjaved/rest_api
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: /usr/src/app/data/database.sqlite  # Explicitly set the writable path
      - key: API_KEY
        sync: false  # You'll set this manually
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
    healthCheckPath: /api/health
    autoDeploy: true